name: Padavan MI-NANO CI
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      VERSION: latest
      tag: Phicomm
      Target: K2P
      URL: https://github.com/hanwckf/rt-n56u
    steps:
    - name: Checkout - clone repository
      uses: actions/checkout@v1
    - name: Install - system build dependencies
      run: sudo apt install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd cpio git python-docutils gettext automake autopoint texinfo build-essential help2man pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev
    - name: Download - openwrt source download
      run: |
        git clone --depth=1 $URL
    - name: Pre Build toolchain - Crosstool-NG
      run: |
        cd rt-n56u
        c_dir=$(pwd)
        sed -i 's/\/opt/$c_dir/g' -r .
        cd toolchain-mipsel
        ./clean_toolchain
        ./build_toolchain
    - name: Ready for Build firmware - Padavan
      run: |
        cd rt-n56u/trunk
        ./clear_tree
    - name: Build - Padavan
      run: |
        cd rt-n56u/trunk
        ./build_firmware_modify K2P
    - name: Release - push to release file
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: rt-n56u/trunk/images/*
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASES_DEPLOY_TOKEN }}
    - name: Upload - push to artifact file
      uses: actions/upload-artifact@v1
      with:
        name: padavan-K2P
        path: rt-n56u/trunk/images/

